### ISSUE TITLE
Requirement to match meta tags in translated markdown seems like an extra work

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#1]
## Background of the problem
When I was trying to translate an English article written in Markdown into Japanese.

## What is the problem
Removing a meta tag (ex: `<br data-md-type="linebreak" data-md-index="64">`) from original content caused an error `Content has missing HTML tag(s)`. 

## How to solve the problem, if you have any idea.
It's preferable if I don't have to deal with any of these meta tags.

**Comment by sotayamashita** [comment]
@agektmr Could you give me the URL?

**Comment by agektmr** [comment]
@sotayamashita I'm currently translating on https://gitlocalize.com/repo/107/ja/src/content/en/updates/2017/06/credential-management-updates.md

**Comment by sotayamashita** [comment]
@agektmr Thanks. I will look into it

**Comment by sotayamashita** [comment]
@agektmr You should have same HTML tag in original docs. 

Why do you want to remove it from Japanese?

**Comment by agektmr** [comment]
I assume the wrap tags are inserted because original Markdown contained them. They are mostly added to align with the style guide (wrap every 80 chars). But in Japanese, aligning such guidance has different effect as
- size of characters are different (usually 2x compared to alphabet chars using static fonts in an editor)
- they may be significantly shorter leaving some wraps out.

**Comment by sotayamashita** [comment]
We can implement the feature to ignore specific HTML tags such as `<br />`.

**Comment by agektmr** [comment]
The most intuitive approach I would appreciate here is to be able to edit the Markdown as a Markdown. But I don't know the rational how it works as it is now. It's up to you.

**Comment by sotayamashita** [comment]
> The most intuitive approach I would appreciate here is to be able to edit the Markdown as a Markdown.

We understand the needs. We cannot show markdown in our current structure but we have an idea to avoid using full HTML tags. Please be patient with me :bow:

**Comment by agektmr** [comment]
I've noticed this is quite problematic. Hope this issue will be resolved soon!

**Comment by sotayamashita** [comment]
@agektmr We have released the feature. It helps people focus on their sentence more than before because GitLocalize replaces **HTML tags** with **our simple format** :100:. For example, if sentence is `<a href="https://example.com">Hello World</a>`,  it will be `{a0}Hello World{/a0}`.

**Comment by chikathreesix** [comment]
@agektmr We implemented not to compare <br> tags in a translation to the ones in its original segments so that it doesn't need to have an exact number of <br> tags as the original segments.
I will close this issue.

**Comment by agektmr** [comment]
Got it. Thanks!
