### ISSUE TITLE
Can’t submit the translation

### ISSUE THREAD

**Issue by inouetakuya** [gitlocalize/feedback#10]
### Summary

I had clicked submit button, but no reaction was shown.

### Steps to reproduce

As the following screenshot, fill in the textbox and click the Submit button.

```
すべてのモジュールが同期的に処理を行うわけではありません。{br0}例えばどこかの API からフェッチしたり IO を非同期的に扱うモジュールを開発したい場合もあるでしょう。{br1}このような場合のために Nuxt は Promise を返したりコールバックを呼び出す非同期モジュールをサポートしています。
```

### Repository URL

https://gitlocalize.com/repo/100/ja/en/guide/modules.md

### What is the current *bug* behavior?

No reaction was shown.

### What is the expected *correct* behavior?

Submitting succeeds.

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/634357/30644918-fe0f8028-9e4e-11e7-9dcd-3c3d163373d6.png)

```
application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:3 
POST https://gitlocalize.com/api/segments/950151/translation 500 ()
send @ application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:3
ajax @ application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:3
value @ editor-47ffc9ec0947d14ddc4513c5dc6f4621c583f881cbbcdd30c5206beb8733b140.js:1
dispatch @ application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:2
m.handle @ application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:2
```

```
VM1747:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.error (editor-47ffc9ec0947d14ddc4513c5dc6f4621c583f881cbbcdd30c5206beb8733b140.js:1)
    at c (application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:2)
    at Object.fireWith [as rejectWith] (application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:2)
    at i (application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:3)
    at XMLHttpRequest.n (application-32d64f080d223f92b1e116cb55c2bc053fab84048863bc2c373a96a9e3c069b6.js:3)
```

### Possible fixes

I see 500 error in abobe console log:

```
POST https://gitlocalize.com/api/segments/950151/translation 500 ()
```

**Comment by sotayamashita** [comment]
@inouetakuya We are sorry about it. We are looking into it.

**Comment by sotayamashita** [comment]
@inouetakuya I have created a pull request for the issue and it will be fixed by today. 

#### The reason for bug and how to prevent.

I forgot to check some self-closing HTML tag on my spec so I added these spec. When I implement features which are related to segment, I will write spec which covers all HTML tags. After fixing this issue, I will create HTML tag list for spec.

We thank you for your patience.

**Comment by sotayamashita** [comment]
@inouetakuya I deployed fixed version. Please check it out. Thanks

**Comment by inouetakuya** [comment]
I have submitted the translation successfully. Thank you for fixing!!
