### ISSUE TITLE
[Bug] Document with conflicts does not open

### ISSUE THREAD

**Issue by vokamut** [gitlocalize/feedback#101]
### Summary

Document with conflicts does not open:
https://gitlocalize.com/repo/5630/ru/documentation.md

500 error at link:
https://gitlocalize.com/api/resources/606129

### Steps to reproduce

Open both links

### Repository URL

https://gitlocalize.com/repo/5630/ru

### What is the current *bug* behavior?

Blank page

### What is the expected *correct* behavior?

There must be a document with source text and translation

### Relevant logs and/or screenshots

Not required

### Possible fixes

Server side error, no ideas

**Comment by svasilenkov** [comment]
Thank you for the feedback. I've forwarded it to our development team. I'll contact you as soon as it is fixed.

**Comment by svasilenkov** [comment]
The repository has been removed from GitHub. @vokamut is this issue still relevant?

**Comment by vokamut** [comment]
I have been waiting for a bug fix for over a month. As a result, I deleted the repository and switched to another platform.
Issue is not relevant.
