### ISSUE TITLE
Wrong order references in translate

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#102]
Hello

I translated this post https://github.com/rust-lang-ru/translations/blob/master/originals/announcements/2021-03-25-Rust-1.51.0.md
here https://github.com/rust-lang-ru/translations/pull/91/files

All references exists, but an order is wrong

for example 

origin

```
[`split-debuginfo`]: https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#split-debuginfo
```

translate

```
[`split-debuginfo`]: https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
```

**Comment by svasilenkov** [comment]
Thank you for reporting the issue, we've placed it in our to-do list.

**Comment by ava57r** [comment]
another example is https://github.com/rust-lang-ru/book/pull/661/files

**Comment by svasilenkov** [comment]
@ava57r We've fixed the problem, please check if links are not replaced now with incorrect ones.

**Comment by ava57r** [comment]
> another example is https://github.com/rust-lang-ru/book/pull/661/files

I checked this file.
It works.

**Comment by ava57r** [comment]
again : -( https://github.com/rust-lang-ru/translations/pull/102
