### ISSUE TITLE
Unable to log into GitLocalized via GitHub SSO

### ISSUE THREAD

**Issue by shuki25** [gitlocalize/feedback#104]
### Summary

Unable to log into GitLocalized via GitHub SSO with an error message, "Your GitHub token has expired. Please try to sign in again." It didn't work even after I removed the token from GitHub settings and tried to log in again, still get the same error message.

### Steps to reproduce

Previously had an account created 2 years ago and not logged in since a year and half ago before you switched over from User/Password authentication/OAuth to GitHub SSO. When trying to log in, it asks me to link it to GitHub sign in, proceed to approve the permission on GitHub page, redirected back to GitLocalize. It fails afterwards.

### Repository URL

(If possible, please paste repository URLs which have errors.)

### What is the current *bug* behavior?

Trying to log in, it redirected me to GitHub to authorize GitLocalize to use GitHub account information. After linking it, it returned to GitLocalize page and got the error message "Your GitHub token has expired. Please try to sign in again". So I tried it again by deleting the token from GitHub and re-authorize, I'm still getting the same error message. I am unable to log into my project. I have some localization work that needs updating. **It is a HIGH PRIORITY fix.** I have a pull request pending and I can't process it until the log in is fixed.

I think the problem here is that a person with existing account which was created two years ago and did not log in for two years and then tries to log in through GitHub SSO and it failed. There is no way to reset the account whatsoever in order to re-link the account to GitHub SSO.

### What is the expected *correct* behavior?

Should be able to log in without any trouble. **You need to have a contingency plan (fail-safe) in case it fails like in my case.**

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/31372342/114311804-3a72d500-9abe-11eb-95fc-655b0156b4b2.png)

### Possible fixes

(If you have any idea to solve the problem, please help us.)

**Comment by svasilenkov** [comment]
Thank you for reporting the issue, I've forwarded it to the development team.

**Comment by svasilenkov** [comment]
@shuki25 The problem has been fixed. Could you please try to log in once again?

**Comment by shuki25** [comment]
This issue was resolved after I emailed the support back in April.
