### ISSUE TITLE
Fix links to segments

### ISSUE THREAD

**Issue by inouetakuya** [gitlocalize/feedback#11]
## Summary

I have made a mistake in linking to segments, so I would like to fix it. :bow:

## Repository URL

https://gitlocalize.com/repo/100/ja/en/guide/modules.md

### Links to fix (1)

![image](https://user-images.githubusercontent.com/634357/31337862-17f21486-ad38-11e7-8718-e319af660449.png)

### Links to fix (2)

![image](https://user-images.githubusercontent.com/634357/31337868-1dc8f744-ad38-11e7-9059-975dbe6d705f.png)

**Comment by sotayamashita** [comment]
We also sometimes make the mistake :smile: and I have fixed the link. Please check it out. 

We have an internal method which makes file be conflict status. Do you want to use this method, if you have the same issue? By the way, we are considering the best way to solve conflict status now. I

**Comment by inouetakuya** [comment]
Thank you for your help!

> Do you want to use this method, if you have the same issue?

Yes, when I make another same mistake someday, I will beg you. :smile:

> By the way, we are considering the best way to solve conflict status now.

Sounds great!! :+1:
