### ISSUE TITLE
Sync with GitHub

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#115]
Hello.

Please, explain how does it work?

Some people like send PR from Github for fixing translation errors.
How does GL sync these from GH.

Thanks.

**Comment by ava57r** [comment]
I can add suggestions in gitlocalize bot PR before merge.
What does it happen with fixes?

**Comment by ilyaspiridonov** [comment]
> 
> Some people like send PR from Github for fixing translation errors. How does GL sync these from GH.
>
Hi, thanks for your inquiry. 
As long as the file is 'Synced' (no open PRs), changes made on the GitHub end should be synced into the GitLocalize project (as GitHub is always used as 'source of truth')

**Comment by ilyaspiridonov** [comment]
> I can add suggestions in gitlocalize bot PR before merge.
> What does it happen with fixes?

@svasilenkov Can you look into this?  My understanding is that we won't be able to 'commit' those suggestions, as the PR is authored by Gitlocalize-bot. 
@ava57r Unless you can commit those suggestions yourself (not sure if GitHub allows to do that)
On another note, Gitlocalize-bot creates a new branch when opening a PR, so in theory you should be able to push changes to that branch from your local git (and those changes  should update the PR created by gitlocalize-bot).

**Comment by ilyaspiridonov** [comment]
What kind of changes in the PR are you referring to? Linguistic (wording, style, grammar etc) or technical (anything GitLocalize may mess with?)

**Comment by ava57r** [comment]
https://github.com/rust-lang-ru/book/pull/1029

**Comment by ava57r** [comment]
> What kind of changes in the PR are you referring to? Linguistic (wording, style, grammar etc) or technical (anything GitLocalize may mess with?)

invalid links
spell checking

https://github.com/rust-lang-ru/book/pull/1029
https://github.com/rust-lang-ru/book/pull/1028

style 
https://github.com/rust-lang-ru/book/pull/1025

**Comment by ava57r** [comment]
> What kind of changes in the PR are you referring to? Linguistic (wording, style, grammar etc) or technical (anything GitLocalize may mess with?)

Gitlocalize does not have spellchecking =(

We check https://github.com/rust-lang-ru/book/blob/master/.github/workflows/main.yml#L18

**Comment by ilyaspiridonov** [comment]
for anything text-related (grammar/spelling etc) you can make changes on Gitlocalize even after creating the PR:

<img width="769" alt="Screenshot 2022-08-24 at 13 11 07" src="https://user-images.githubusercontent.com/8548803/186392671-85074467-59ee-483b-8841-d54fa19672b5.png">

Updates will be sent as a separate commit to the same branch (i.e. will appear on the same PR)

**Comment by ilyaspiridonov** [comment]
For the links: does this keep happening often or was that a more like a one-off case scenario?

**Comment by ava57r** [comment]
> For the links: does this keep happening often or was that a more like a one-off case scenario?

rarely

Some people don't want to use your system
One of reasons pipeline 
translate -> create GL PR (translator) -> create GH PR(moderator)

They like to create GH PR directly.

**Comment by ava57r** [comment]
> > I can add suggestions in gitlocalize bot PR before merge.
> > What does it happen with fixes?
> 
> @svasilenkov Can you look into this? My understanding is that we won't be able to 'commit' those suggestions, as the PR is authored by Gitlocalize-bot. @ava57r Unless you can commit those suggestions yourself (not sure if GitHub allows to do that) On another note, Gitlocalize-bot creates a new branch when opening a PR, so in theory you should be able to push changes to that branch from your local git (and those changes should update the PR created by gitlocalize-bot).

I added suggestions here
https://github.com/rust-lang-ru/book/pull/1029

after merge segments were untranslate in GL.

I created a new PR from GL
https://github.com/rust-lang-ru/book/pull/1030

**Comment by ava57r** [comment]
batch fix 
https://github.com/rust-lang-ru/book/pull/1025

it easier to fix from git then GitLocalize web interface

**Comment by svasilenkov** [comment]
> @svasilenkov Can you look into this? My understanding is that we won't be able to 'commit' those suggestions, as the PR is authored by Gitlocalize-bot.
> @ava57r Unless you can commit those suggestions yourself (not sure if GitHub allows to do that)
> On another note, Gitlocalize-bot creates a new branch when opening a PR, so in theory you should be able to push changes to that branch from your local git (and those changes should update the PR created by gitlocalize-bot).

@ilyaspiridonov I have tested the following:

1. Created review request in GitLocalize.
2. Created pull request authored by GitLocalize.
3. Made a commit into the pull request at GitHub with some changes.
4. Merged the pull request.
5. GitLocalize successfully synced from GitHub all changes made at the step 3.
