### ISSUE TITLE
Unrendered original parts of text with code

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#117]
Hello.
I found parts without rendering
as 

`{code0}{/code0}`
`{code1}{/code1}`
![изображение](https://user-images.githubusercontent.com/20382553/198962270-141bdcf1-653e-4277-b2cc-936294710cbb.png)

from this file https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch04-03-slices.md

**Comment by svasilenkov** [comment]
@ava57r Thanks for reporting this, it will be fixed shortly.
