### ISSUE TITLE
Avoid multiple PR for every single .po file

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [gitlocalize/feedback#118]
I am using Sphinx ReadtheDocs for my project. For every `.po` file that is translated, there is a separate PR that gets created. If I have 50 `.po` files, is this behavior normal?

If I have a single language translated PR, I can use that branch to point it to Sphinx ReadtheDocs.

**Comment by ilyaspiridonov** [comment]
@sachin-suresh-rapyuta Thanks for the issue.  This is actually implemented already: 
1) Create a review request (file 1)
2) create a review request (file 2)
3) Head to review requests, select both files and send a single PR:
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/8548803/198974309-9c1cc837-fa9f-44e4-958a-e84aa0bfd44a.png">

Closing this for now as this doesn't seem to be an active issue, but please feel free to comment/reopen if you have other questions or concerns. 
Thanks!

**Comment by sachin-suresh-rapyuta** [comment]
Thanks. Just curious, which algorithm does the machine translation use- DeepL or Google Translation?

**Comment by ilyaspiridonov** [comment]
@sachin-suresh-rapyuta It's currently Google Translate, but we'll be adding other engines for enterprise clients
