### ISSUE TITLE
Cannot create GitHub PR in Review Request tab

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/feedback#12]
### Summary
Recently, With the recent release of Vue 2.5, the documentation of Vue SSR docs has also been updated. 

In README.md, I have completed the difference translation (100%).

### Steps to reproduce
1. translate new segument at https://gitlocalize.com/repo/101/ja/en/README.md
2. translate it.
<img width="1174" alt="screen shot 2017-10-15 at 1 21 21" src="https://user-images.githubusercontent.com/72989/31577365-ee13adc8-b147-11e7-991f-a9e9abbcb0c9.png">
3. move Review Reuqest tab via [Currently in Review Request] link
<img width="1177" alt="screen_shot_2017-10-15_at_1_26_27" src="https://user-images.githubusercontent.com/72989/31577386-43cdcece-b148-11e7-9e9b-2f050719a5bd.png">

### Repository URL
https://gitlocalize.com/repo/101/ja/review/169

### What is the current *bug* behavior?
I cannot create GitHub PR ...
<img width="1189" alt="screen_shot_2017-10-15_at_1_30_10" src="https://user-images.githubusercontent.com/72989/31577401-9576d798-b148-11e7-8015-52e2b98a8666.png">

### What is the expected *correct* behavior?
We should create GitHub PR!

### Relevant logs and/or screenshots
I pasted to above sections

**Comment by kazupon** [comment]
additional issue:
https://gitlocalize.com/repo/101/ja/review/255

**Comment by chikathreesix** [comment]
Looking into it. Sorry for the inconvenience.

**Comment by chikathreesix** [comment]
Recreate a review request, resend a pull request and it went successfully

**Comment by kazupon** [comment]
Thanks!

**Comment by kazupon** [comment]
hmm 🤔, I cannot create PR ...
https://gitlocalize.com/repo/101/ja/review/255
