### ISSUE TITLE
[Feature Request] Add West African Pidgin English as language

### ISSUE THREAD

**Issue by mtdvlpr** [gitlocalize/feedback#121]
### Summary

I have a user who wants to translate in West African Pidgin English. Could you add this language to the language dropdown? Either that or allow a custom input like stated in https://github.com/gitlocalize/feedback/issues/111

https://en.wikipedia.org/wiki/West_African_Pidgin_English

**Comment by svasilenkov** [comment]
@mtdvlpr Thank you for your request. This language has many local varieties with their own ISO 639-3 language codes, including Sierra Leone Krio (kri), Nigerian Pidgin (pcm) and other. Could you please specify which ones you would like to be added.

**Comment by mynetx** [comment]
If we can add Nigerian Pidgin, this will be helpful. 😊 It's the closest...

**Comment by mtdvlpr** [comment]
Nigerian Pidgin it is!

**Comment by mtdvlpr** [comment]
@svasilenkov, any indication when this might be added?

**Comment by svasilenkov** [comment]
@mtdvlpr Nigerian Pidgin language support has been added. Please try if it works well.

**Comment by mtdvlpr** [comment]
@svasilenkov, It works perfectly, thanks!
