### ISSUE TITLE
[feature] API for translation progress

### ISSUE THREAD

**Issue by DreamOfIce** [gitlocalize/feedback#129]
I would like to be able to show the current progress of the translation on the documentation site.

Maybe an API like https://developer.crowdin.com/api/v2/#operation/api.projects.branches.languages.progress.getMan could be added, and it would be nice to be able to access it without authorization 😄

**Comment by ilyaspiridonov** [comment]
@DreamOfIce Hey, thanks for reaching out. Would a badge work? https://gitlocalize.com/repo/**XXXX**/badge

**Comment by ilyaspiridonov** [comment]
![image](https://user-images.githubusercontent.com/8548803/227292042-f02a9520-cc0f-464f-9e96-c74241863f34.png)

**Comment by ilyaspiridonov** [comment]
![image](https://user-images.githubusercontent.com/8548803/227292255-a89d4fc3-feca-4ba3-a05d-72f3e11eaf45.png)

**Comment by DreamOfIce** [comment]
This fulfills part of my need, but I'd like to achieve something like this (taken from pnpm.io)
![D16373E6-1CA0-45FB-9ABA-322B42B5F124](https://user-images.githubusercontent.com/80821706/227462437-2a334a96-af67-417a-ae08-3cd8b9b5df35.jpeg)
It looks like maybe I can extract the progress text from the SVG of the badge?

**Comment by svasilenkov** [comment]
@DreamOfIce Yes, it can be taken from SVG:

![image](https://user-images.githubusercontent.com/52036683/227555673-6fafac8f-1073-45db-88d6-d910c2727eb7.png)
