### ISSUE TITLE
[Feature Request] 翻訳元の更新に伴う再翻訳のUX改善

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/feedback#13]
# summary
現時点の仕様ですが、翻訳元が更新されると、翻訳先が上書きされる仕様になっています。
現時点では、例えば単語やtypoでも更新されると、翻訳先が翻訳元の内容で全て上書きしてしまいます。

ケース: Vue 2.5 アップグレートに伴う vue-ssr-docs (en) の更新
- basic.md at gitlocalize: https://gitlocalize.com/repo/101/ja/en/basic.md
<img width="1196" alt="screen shot 2017-10-15 at 1 48 36" src="https://user-images.githubusercontent.com/72989/31577546-86e309c4-b14b-11e7-9ea0-e42f1d4a1ca1.png">

- basic.md at github: https://github.com/vuejs/vue-ssr-docs/blob/master/ja/basic.md
<img width="1058" alt="screen shot 2017-10-15 at 1 48 47" src="https://user-images.githubusercontent.com/72989/31577541-7d347a5c-b14b-11e7-9748-6152c2b65efd.png">

- 参考: 更新 commit 
https://github.com/vuejs/vue-ssr-docs/commit/2f79a56f459894c8e96728b4243db70bd8b4e9f5
<img width="1043" alt="screen shot 2017-10-15 at 1 51 36" src="https://user-images.githubusercontent.com/72989/31577553-94f9e834-b14b-11e7-9d92-1afc052015a9.png">

### Repository URL
https://gitlocalize.com/repo/101

### Possible fixes
単語、typoレベルで翻訳元が更新された際に対象となる翻訳先が全て上書きされてしまうのは、一から翻訳するのは手間がかかります。
GitHubのrepoにある翻訳された対象の部分をコピペしてから、更新差分を適用するのも結構手間がかかります。

Gitlocalizeで対象セグメントにおいて翻訳履歴がポップアップかモーダルかなんかで、直前翻訳の履歴が見れるとそこを参考にできるので、翻訳UX改善のために、そのような何らかアシストがあると助かります。

**Comment by chikathreesix** [comment]
まさしく今取り組んでいるところです！　翻訳メモリを実装しており、過去の類似した翻訳をrecommendできるようになります。また進捗をお伝えします。

**Comment by sotayamashita** [comment]
一度クローズします。再度翻訳メモリをりりーすしましたら共有致します
