### ISSUE TITLE
Services Down

### ISSUE THREAD

**Issue by NonSpicyBurrito** [gitlocalize/feedback#135]
### Summary

GitLocalize services are down.

### Steps to reproduce

Create pull request, or sync project.

### What is the current *bug* behavior?

Creating pull request fails, and syncing project does not sync.

### What is the expected *correct* behavior?

They should work.

**Comment by svasilenkov** [comment]
@NonSpicyBurrito Thank you for the feedback. Could you please give us example of a resource you are having problems with.

**Comment by NonSpicyBurrito** [comment]
All of my repos are having the issue (unable to sync/create pull requests), here is one:
https://gitlocalize.com/repo/7739

**Comment by svasilenkov** [comment]
@NonSpicyBurrito Thank you for the repository link, our developers will check your projects to find the cause of the problem.

**Comment by svasilenkov** [comment]
@NonSpicyBurrito It looks like you have revoked access to your repositories for GitLocalize GitHub App application. To fix the problem with sync and pull request creation please grant access to the repositories using this link:

https://github.com/apps/gitlocalize-app/installations/new

**Comment by NonSpicyBurrito** [comment]
That was the issue, thank you.
I would suggest to improve error handling and messages so users can be made aware of the issue.
