### ISSUE TITLE
Cannot create a GitHub PR even after retrying

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/feedback#14]
### Summary
Related #12
In api.md, I have completed the difference translation (100%).

### Steps to reproduce
1. Retry create a GitHub PR: https://gitlocalize.com/repo/101/ja/review/269
<img width="1177" alt="screen shot 2017-10-15 at 2 37 21" src="https://user-images.githubusercontent.com/72989/31577933-0ee09f34-b152-11e7-93a4-700e359a4ee1.png">

2. after in reiewe request page, reload
<img width="1192" alt="screen shot 2017-10-15 at 2 38 13" src="https://user-images.githubusercontent.com/72989/31577935-1310113e-b152-11e7-8c4a-3c529c9eac88.png">

### Repository URL
https://gitlocalize.com/repo/101/

### What is the current *bug* behavior?
Cannot create a GitHub PR ...

### What is the expected *correct* behavior?
We should create a GitHub PR.

### Relevant logs and/or screenshots
I pasted to above sections

**Comment by chikathreesix** [comment]
I found a bug in this case and fixed it. The pull request has been sent now.
I will close this issue.

**Comment by kazupon** [comment]
Thanks!
