### ISSUE TITLE
Occured Conflict When merged PR that created with GItLocalize

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/feedback#15]
### Summary
Related #12 

Occured Conflict When merged PR that created with GItLocalize ...

### Repository URL
https://gitlocalize.com/repo/101/

### What is the current *bug* behavior?
In GitLocalize, Occured conflict 
https://gitlocalize.com/repo/101/ja/en/SUMMARY.md

### What is the expected *correct* behavior?
It should not conflict in SUMMARY.md

### Relevant logs and/or screenshots
- State of SUMMARY.md in GitHub repo
https://github.com/vuejs/vue-ssr-docs/pull/145/files

- State of GitHub PR in Review Reqeust page
https://gitlocalize.com/repo/101/ja/review/270

**Comment by chikathreesix** [comment]
Found a bug in a nested list. Fixed it and send a pull request for SUMMARY.md so when you merge it, it should work fine. I will close this issue.

**Comment by kazupon** [comment]
Thanks!
