### ISSUE TITLE
Changed directories show both original and translated tree architecture

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#17]
### Summary
When a file or a directory is moved to another location, GitLocalize shows both original and new file/directory.

### Steps to reproduce
See this directory:
https://gitlocalize.com/repo/107/ja/src/content/en/fundamentals

`discovery-and-monetization/payment-request` directory is moved to `payments`, but it shows both directories.

I suspect this is due to one of files is half being translated.
https://gitlocalize.com/repo/107/ja/src/content/en/fundamentals/discovery-and-monetization/payment-request/payment-request-ux-considerations.md

### What is the expected *correct* behavior?
I'm not sure what is going on, but what about showing older directory in slightly lighter color?
Letting me know why this is happening is also definitely helpful.

**Comment by chikathreesix** [comment]
@agektmr , I apologize for our late response. I believe this issue has been fixed but let me double check.

**Comment by sotayamashita** [comment]
@agektmr I have check it our in local and production. It works well. Let us know if you have any additional issue!
