### ISSUE TITLE
[Feature Request] Create PR without creating all translation of Code blocks

### ISSUE THREAD

**Issue by cwdoh** [gitlocalize/feedback#18]
### Summary

If translator doesn't make sure of creating a translation of code block, it doesn't show 'Create PR' button.

### Steps to reproduce

1. translate all paragraph except code block.
2. Its progress doesn't reach to 100% and `Create PR`button won't be enabled.

### Repository URL

I've cleared this issue by just creating translation block of code without real translating.

### What is the current *bug* behavior?

Code block is a special case of translations, we don't translate them
if they don't include some comments.

### What is the expected *correct* behavior?

If the translator did all translation except code blocks, `Create PR` button should be shown.
I guess most language moderators and reviewers will address it if they think it's needed.
And an alternative way is that show approve button or tag, some code block isn't translated.

### Relevant logs and/or screenshots

I solved this issue by the [following commit](https://gitlocalize.com/repo/107/ko/activities). :)

```	
cwdoh created a ko translation "paulkinlan: name: given: Paul family: Kinlan org: name: Google unit: Developer Relations country: UK role: - author - engineer - translator homepage: http://paul.kinlan.me google: +PaulKinlan twitter: paul_kinlan email: paulkinlan@google.com description: en: "Paul is a Developer Advocate" "
18 minutes
```

### Possible fixes

(If you have any idea to solve the problem, please help us.)
I wrote them up on expected behavior. :)

**Comment by cwdoh** [comment]
and what do you think about parsing code blocks and if there is no comment block. it also be treated as translated. (Sure string block will be option.)

**Comment by sotayamashita** [comment]
@cwdoh We will release the feature soon. We appreciate your feedback
