### ISSUE TITLE
Comment on specific text or translation block when review the translation

### ISSUE THREAD

**Issue by tyohan** [gitlocalize/feedback#24]
On reviewing the translation, it's really hard for me to back and forth between translated texts and conversations to comment which words should be replace, or those words are not correct. And it's hard which part of translation that need to be fix. I think Google docs comment system model will be really help on giving feedback to those translations.

Check my attachment below to see how I think should be better on reviewing the translation.
![image](https://user-images.githubusercontent.com/106703/33109985-7638f8a0-cf77-11e7-94f4-cc994b680fd3.png)

**Comment by sotayamashita** [comment]
@tyohan I appreciate your feedback. Is it possible to paste the link?

**Comment by tyohan** [comment]
Can you elaborate what link that you mean? @sotayamashita

**Comment by sotayamashita** [comment]
@tyohan I am sorry. I misunderstood. I completely understand the point. We are considering the great way to improve reviewing. Thank you for the feedback
