### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by AlanCezarAraujo** [gitlocalize/feedback#26]
### Summary

I can't save HTML content to `yaml` files. It gets me the error `Content has missing HTML tag(s)`.

### Steps to reproduce

1. Edit some HTML content in a `.yaml` file like `<p>boom!</p>`.
2. Click the **submit** button to get the `Content has missing HTML tag(s)` error.

### Repository URL

https://gitlocalize.com/repo/107

### What is the current *bug* behavior?

I send valid HTML content, but the API always returns some parsing error. 

### What is the expected *correct* behavior?

It should save the data.

**Comment by sotayamashita** [comment]
@AlanCezarAraujo Sorry for the inconvenience. I would appreciate if you could us the link. Thanks

**Comment by agektmr** [comment]
https://github.com/google/WebFundamentals/pull/5313

**Comment by sotayamashita** [comment]
@agektmr I appreciate you gave me the link

**Comment by agektmr** [comment]
I think this issue is outdated. Please consider closing.
