### ISSUE TITLE
mt@gitlocalize.com doesn't match CLA

### ISSUE THREAD

**Issue by lucab85** [gitlocalize/feedback#30]
### Summary

mt@gitlocalize.com doesn't match any CLA

### Steps to reproduce

The sender of this commit is "mt@gitlocalize.com" 
https://github.com/lucab85/WebFundamentals/commit/b92b2cb9185a4f5b3318e5d70964ef6f7ae7dcf3

### Repository URL

https://gitlocalize.com/repo/107/

### What is the current *bug* behavior?

Git sender is "mt@gitlocalize.com"

### What is the expected *correct* behavior?

Git sender should be my github login.

### Possible fixes

"machine-translation" text could be insert into commit body.

**Comment by sotayamashita** [comment]
@lucab85 We have signed Corporate CLA yesterday and are waiting until it is allowed.

**Comment by agektmr** [comment]
Let's consider this sorted. Please close the issue.

**Comment by sotayamashita** [comment]
@agektmr thanks
