### ISSUE TITLE
Linkage broken

### ISSUE THREAD

**Issue by kennith** [gitlocalize/feedback#35]
### Summary

The paginate linkage links to incorrect page.

### Steps to reproduce

1. Go to https://gitlocalize.com/repo/107/zh-TW/activities/src/content/en/_footer.yaml
2. Link on 2 in the paginate.
3. Instead taking to the next page of a specific file, it takes the user to all the activities of a translation repo. 

### Repository URL

https://gitlocalize.com/repo/107/zh-TW/activities/src/content/en/_footer.yaml

### What is the current *bug* behavior?

Linkage is broken.

### What is the expected *correct* behavior?

It should show the remaining activity result of a specific file. 

### Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/871161/33455817-21cbada6-d5d2-11e7-90a3-01c94831b6e4.png)

After clicking to the next page, it takes a user to:
![image](https://user-images.githubusercontent.com/871161/33455864-3ba2bac6-d5d2-11e7-9026-9b98078c7721.png)

### Possible fixes

(If you have any idea to solve the problem, please help us.)

The correct URL is https://gitlocalize.com/repo/107/zh-TW/activities/src/content/en/_footer.yaml?limit=30&offset=30

Missing the [src/content/en/_footer.yaml]

**Comment by sotayamashita** [comment]
#ref 38

**Comment by sotayamashita** [comment]
@kennith We are sorry not to replay quickly. Fixed version is landed :tada:. Thanks
