### ISSUE TITLE
[Feature request] floating translation parts when scrolling to link to a segment

### ISSUE THREAD

**Issue by cwdoh** [gitlocalize/feedback#37]
### Summary

* Floating translation parts when scrolling to link to a segment is better UX than holding its positions.

### Steps to reproduce

1. Find some docs to be needed linking to a segment.
2. Try all paragraphs to their segments.
3. If differences of vertical position between source and translation would be bigger, scroll many times to the next segment.

### Repository URL

* [my case](https://gitlocalize.com/repo/107/ko/src/content/en/fundamentals/performance/critical-rendering-path/analyzing-crp.md)

### What is the current *bug* behavior?

* it's not bug, however if it would be taken a long time, it can be a pain-point works before real translation.

### What is the expected *correct* behavior?

* Floating unresolved paragraphs to follow scroll, it makes easy to do next linking to a segment.

### Relevant logs and/or screenshots

* :)

### Possible fixes

* I wrote it in expected behavior.

**Comment by chikathreesix** [comment]
Thanks for the report, @cwdoh! We are actually working on it and will be released in a week. We will let you know once it goes live.
