### ISSUE TITLE
Pagenation in "activities" is busted.

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#38]
### Summary

"Activities" page both under project nor language can not move forward.

### Steps to reproduce

Go https://gitlocalize.com/repo/107/activities
Press any page numbers. It won't move although query param `offset` is changing.

### Repository URL

https://gitlocalize.com/repo/107/

### What is the current *bug* behavior?

It won't move although query param `offset` is changing.

### What is the expected *correct* behavior?

Pagenate to see further activities.

**Comment by sotayamashita** [comment]
@agektmr We are sorry about it. We will look into it.

**Comment by sotayamashita** [comment]
@agektmr fixed version landed :bow: I have added test code. We apologize for any inconvenience
