### ISSUE TITLE
翻訳対象元のドキュメント構造変更に伴うConflictが発生したときの対処について

### ISSUE THREAD

**Issue by kazupon** [gitlocalize/feedback#4]
## GitLocalize URL, if you have problem on GitLocalize
https://gitlocalize.com/repo/101/ja/en/build-config.md

## Background of the problem
[`open-source-translators/vue-ssr-docs`](https://github.com/open-source-translators/vue-ssr-docs)にて日本語翻訳が完了し、本家`vuejs/vue-ssr-docs`にマージした。

## What is the problem
日本語翻訳の最中期間に、大元の`vuejs/vue-ssr-docs`のドキュメントに更新あり、一部ドキュメント追加により、ドキュメント構造が変更したが、追加された部分をどう対応していいのか分からない。以下画像を参照。

<img width="981" alt="screen_shot_2017-07-10_at_12_37_34_am_gitlocalize" src="https://user-images.githubusercontent.com/72989/27995478-09515a5c-650a-11e7-9b9c-314e4a8f9d1d.png">

## How to solve the problem, if you have any idea.
大元のドキュメント構造に変更あった場合のことを考えて、翻訳対象先に自分で翻訳対象先にセグメントを追加できるようにし、翻訳対象元セグメントと翻訳対象先セグメントが互いにリンクして、追従出来るようにすると、柔軟に対応できると思います。

**Comment by sotayamashita** [comment]
@kazupon 

**原因**  
オリジナルの文章が途中に入ってしまったことによって英語と日本語の関連性が崩れてしまっています。

**解決方法**  
今ある英語と日本語を正しく紐付けることによってコンフリクトは解消します。[api.md](https://gitlocalize.com/repo/101/ja/en/api.md) を修正したのでご確認ください。

**Comment by kazupon** [comment]
@sotayamashita ありがとうございます！了解です！

**Comment by agektmr** [comment]
同様の問題は今後も頻繁に発生する可能性があり、根本的な解決になっていません。今後作業者が問題を解消する手立てを用意される予定はありますでしょうか？

**Comment by chikathreesix** [comment]
こちら原因が他にあるような気がします。確認しますので少々お待ちください。

**Comment by chikathreesix** [comment]
こちらですが、MarkdownパーサーのRedcarpetのパースに問題があることが分かりました。Web Fundamentalsでも問題が発生していたため、GitHubで使用されているcommon mark互換のものに変更するように早急に対応いたします。ご迷惑おかけしてしまい大変申し訳ありません。 @agektmr @kazupon

**Comment by chikathreesix** [comment]
昨日MarkdownパーサーをCommon Markに変更した修正をリリースしました。これまでmarkdownのインデントが認識されていなかったりしたことで、pull requestをマージ後conflictしてしまうようなバグがあったのですが、こちらで挙動がかなり安定したかと思います。

**Comment by kazupon** [comment]
対応ありがとうございます！
