### ISSUE TITLE
Partial correction of a translation severely damage original

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#40]
### Summary

I made correction to an existing translation and sent a [pull request](https://github.com/google/WebFundamentals/pull/5671). But it turned out include a lot more changes than I had expected.

### Possible fixes

Make pull requests change only the portion user intends to change.
I'd also like to see a diff before sending a pull request.

**Comment by agektmr** [comment]
The portion I have changed are only L186 and L355 in https://github.com/google/WebFundamentals/pull/5671/files#diff-247b8fd717789dfd9b090f59b83608efR355

**Comment by sotayamashita** [comment]
@agektmr We will discuss it. I will share the result. We appreciate.

**Comment by agektmr** [comment]
@sotayamashita What is the status of this issue? I consider this critical.
