### ISSUE TITLE
Can't sync the document to the latest

### ISSUE THREAD

**Issue by re-fort** [gitlocalize/feedback#5]
## GitLocalize URL, if you have problem on GitLocalize
https://gitlocalize.com/repo/110/ja/docs/en/contributing.md

## What is the problem
When I sync the document at GitLocalize's setting page, it seems not to sync the document to the latest. 
Incorrect:
`To ensure all JS follows basic triple make sure it follows these rules.`
Correct:
`To ensure all JS follows basic style standards make sure it follows these rules.`

Is there a delay in sync?

**Comment by re-fort** [comment]
I thought it was a synchronization problem, but the original file has only one commit history, so it seems to be another problem.

**Comment by sotayamashita** [comment]
@re-fort Sorry not to reply your feedback. We will investigate it and provide the way not to reproduce the problem ever.
