### ISSUE TITLE
Can't register repo

### ISSUE THREAD

**Issue by dimaqq** [gitlocalize/feedback#52]
### Summary

Can't register repo.
Whatever I do, I get `Failed to integrate with your repo. Check if the repo, the branch name and the src path exist.`

### Steps to reproduce

connected my account, public repos only
tried to connect my repo dimaqq/kanji-sudoku
this repo has only one branch, `gh-pages` maybe that's the problem?
I've created top-level `int/en/demo.md` and `int/ja` for test translations, but no luck...

### Repository URL

https://github.com/dimaqq/kanji-sudoku

**Comment by nansy-kos** [comment]
Hi, @dimaqq,

Thanks for posting the issue. We have fixed the problem with one-branch repos - your assumption was right. Now you can connect the repo to GitLocalize and start translating the content. 

Should you have any further issues, do not hesitate to post them here.

Sincerely,
Anastasiya

**Comment by dimaqq** [comment]
Thank you so much and sorry it took me a while to get back!
Indeed, my single-branch repo works now, I'm continuing to test your service :)
