### ISSUE TITLE
error connecting to redis

### ISSUE THREAD

**Issue by dimaqq** [gitlocalize/feedback#53]
* made some translations
* left a comment
* clicked create PR
* left PR message
* clicked the button to actually create pull request

Following popped up at the top of the page:

```
Error connecting to Redis on redis-16250.c8.us-east-1-2.ec2.cloud.redislabs.com:16250 (Errno::ECONNREFUSED)
```

**Comment by dimaqq** [comment]
<img width="968" alt="Screenshot 2019-04-11 at 15 25 10" src="https://user-images.githubusercontent.com/662249/55935298-3cef8980-5c6e-11e9-8a4d-7fb0b7092ab4.png">

now the process is stuck:
* reloading the page — no change, stuck on some long poll request
* going to edit the file again — new content is visible on gitlocalize, no option to "submit" changes
* made dummy changes — still no option to "submit" changes (?)
* made a dummy change in source document, machine translated — still no option to "submit" changes :(

(?) maybe it's because gitlocalize thinks that translations are at 100%

https://gitlocalize.com/repo/1883/ja/int/en/en.yml
source document:
https://github.com/dimaqq/kanji-sudoku/blob/gh-pages/int/en/en.yml

**Comment by nansy-kos** [comment]
Hi @dimaqq!

Thanks for letting us know about the issue, we are investigating the Redis problem now. I will contact you as soon as it is solved. 

Regarding the _"Submit changes"_ option. Actually, all the changes you make during the _"Currently in review request"_ mode affect the ongoing Review request - you can see it in the _Translated texts_: https://gitlocalize.com/repo/1883/ja/review/8735/segments. In other words, they are automatically submitted.
Once the pull request is created, you can send the forthcoming changes to the translation as additional commits to the existing pull request (see here: https://prnt.sc/n5uxac). 
Once the pull request is merged, you will be able to make changes to the translation and create another review request.

**Comment by nansy-kos** [comment]
@dimaqq Hi again!

We hope we solved the issue with Redis. To be 100% sure I would ask you to repeat the process - the way you have done lately:

- click on Create Review Request
- leave a comment
- click create PR
- leave PR message
- send PR

https://gitlocalize.com/repo/1883/ja/int/en/en.yml

This time it should go well :)  

Sorry for inconvenience and thanks a lot for your comment - it really helped us to notice the problem. Please make me aware of whether you succeed to send a pull request.

**Comment by dimaqq** [comment]
Yep, works like a charm!
Thank you :)
