### ISSUE TITLE
Non selectable code blocks

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#55]
### Summary

Some code blocks in markdown files (maybe only Rust-specific derivation) not detects as segment.

### Steps to reproduce

1. Open [repo](https://gitlocalize.com/repo/2509/ru/rust-by-example/src/flow_control/if_let.md)
2. Try to translate first code block (fail, not selectable)
3. Try to translate second code block (success, selectable).

### Repository URL

https://gitlocalize.com/repo/2509/ru/rust-by-example/src/flow_control/if_let.md

### What is the current *bug* behavior?

Some code block not selectable.

### What is the expected *correct* behavior?

Code blocks can be selectable for translation like other blocks.

**Comment by svasilenkov** [comment]
Has been fixed, please check this out.

**Comment by funkill** [comment]
Not work.

Tested in Safari 13.0 (15608.1.31.1.2), Firefox 70.0a1 (2019-07-08) on MacOS and Firefox 67.0.4 on Linux

**Comment by svasilenkov** [comment]
It is finally done, now it should work as expected.

**Comment by funkill** [comment]
Thank you! Works great!

**Comment by funkill** [comment]
Found new non selectable code block in 
https://gitlocalize.com/repo/2509/ru/rust-by-example/src/std_misc/path.md,
https://gitlocalize.com/repo/2509/ru/rust-by-example/src/std/str.md,
https://gitlocalize.com/repo/2509/ru/rust-by-example/src/testing/unit_testing.md
and https://gitlocalize.com/repo/2509/ru/rust-by-example/src/std_misc/threads/testcase_mapreduce.md

**Comment by svasilenkov** [comment]
The problem has been fixed for these files too.

**Comment by funkill** [comment]
Thanks!
