### ISSUE TITLE
Can't link translated segment to original in file with conflicts

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#56]
### Summary

In file with conflicts translated segment not links to original segment.

### Steps to reproduce

1. Open [repo](https://gitlocalize.com/repo/2509/ru/rust-by-example/src/SUMMARY.md)
2. Find by path `Атрибуты` -> `cfg (условные атрибуты)` -> `Собственные условия` in translation or `Attributes` -> `cfg` -> `Custom` in original
3. Try to connect `Собственные условия` to `Custom`

### Repository URL

https://gitlocalize.com/repo/2509/ru/rust-by-example/src/SUMMARY.md

### What is the current *bug* behavior?

Translated segment not connected to original

### What is the expected *correct* behavior?

Translated segment connected to original

**Comment by svasilenkov** [comment]
Has been fixed.

**Comment by funkill** [comment]
Work. Thanks!
