### ISSUE TITLE
Article after RR, PR and syncing marked as in "conflict"

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#59]
Issue looks like a consequence of #58 issue, but in this issue more accent to adding some paragraphs to translation and splitting up addition paragraphs after synchronization. Also it may be not a bug, but a feature request.

### Summary

Because source file has segment with two paragraphs, translation also has two paragraphs in one segment. Sometimes we need add new paragraph to segment (in "meta" file with information about source and translation). After synchronization GitLocalize duplicate second paragraph and marked translation as in "conflict".

### Steps to reproduce

1. Open [repo page](https://gitlocalize.com/repo/2509/ru/rust-by-example/src/testing/dev_dependencies.md)
2. Translate  paragraph 
> One such example is using a crate that extends standard `assert!` macros.
>
> File `Cargo.toml`:
4. Accept Review Request
5. Send and merge Pull Request
7. Synchronize book

### Repository URL

https://gitlocalize.com/repo/2509/ru/rust-by-example/src/testing/dev_dependencies.md

### What is the current *bug* behavior?

Second paragraph duplicates after synchronization and file marked as in "conflict"

### What is the expected *correct* behavior?

Both paragraph saved in one segment and file don't marked as in "conflict".

**Comment by svasilenkov** [comment]
Please try to implement some changes suggested here: https://github.com/gitlocalize/feedback/issues/58#issuecomment-514151312
to see if syncing problem is still in place.

**Comment by funkill** [comment]
Thank you!
