### ISSUE TITLE
Content has missing HTML tag(s) エラーを解消できない

### ISSUE THREAD

**Issue by inouetakuya** [gitlocalize/feedback#6]
### Summary

`Content has missing HTML tag(s)` エラーを解消できない

### Steps to reproduce

![image](https://user-images.githubusercontent.com/634357/29973557-f2806184-8f6a-11e7-8507-88691f242641.png)

この場所に下記を入力して Submit をクリックするとエラーが発生します。

```
もし何らかの理由でサーバーサイドレンダリングを使いたくない、あるいはアプリケーションを静的にホスティングする必要があるときは <code data-md-type="codespan" data-md-index="144">nuxt --spa</code> を使って、シンプルに SPA モードを使うことができます。静的ファイル生成機能と組み合わせることで、Node.js ランタイムや特別なサーバー処理を利用する必要のない、SPA のパワフルなデプロイが実現できます。
```

### Repository URL

https://gitlocalize.com/repo/100/ja/en/guide/index.md

### What is the current *bug* behavior?

`Content has missing HTML tag(s)` エラーが発生する

### What is the expected *correct* behavior?

`Content has missing HTML tag(s)` エラーが発生せずに Submit が完了する

### Possible fixes

https://github.com/gitlocalize/feedback/issues/1#issuecomment-310969145

を見ながら、HTML タグが同じなら良いかと思って code タグを入れたのですがエラーが解消できなかったのでちょっと思いつかないです。

### Other

翻訳作業当初、GitLocalize 上で英語と日本語との間にズレが生じていた。

![image](https://user-images.githubusercontent.com/634357/29973571-ff2f15f6-8f6a-11e7-9a4c-96b95a589df7.png)

3つの段落があるが、

* 最初の `If for ...` に対して、当初 `コマンドについて...` が対応しており、
* 次の `Take a look...` に対して、`既にサーバーがあるならば` が対応しており、
* `If you already` に対しては、日本語欄に英語がそのまま掲載されていた。

そのズレを手動で修正したのだが、何か関係している？

### My stance

* 他に翻訳する箇所はたくさんあるので、緊急ではないです
* 9月半ばまでに解消できれば、くらいの気持ちでいます
* github.com の nuxt/docs リポジトリにこんな感じでプルリク投げたら解消するかもよ？くらいの雑なアドバイスでも全然かまわないです
* 何かこれ試してみて？とかは雑にカジュアルに言ってもらってまったく構わないですー 😄

**Comment by inouetakuya** [comment]
@sotayamashita 

GitLocalize - Continuous Localization Tool for GitHub repository
https://gitlocalize.com/repo/100/ja/review/264/segments

いつの間にかエラーが解消されていました。もしかして対応してくださったのでしょうか？:smile:

**Comment by sotayamashita** [comment]
@inouetakuya 

HTMLタグを `{}` というように抽象的なタグに変更する機能をリリースしたんですが
その際にテストの追加とリソースの再度読み込んだので修正されているかもしれません。
ご迷惑おかけして申し分けありませんでした。

引き続きよろしくお願いいたします

**Comment by inouetakuya** [comment]
なるほど、理解しました。ありがとうございます！こちらこそ、よろしくお願いいたします！
