### ISSUE TITLE
Review requests with identical changes

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#60]
### Summary

In unchanged pages shows button "Create Review Request" and after sending to RR, updated segments identical to previous updated segments.

### Steps to reproduce

1. Open translated, reviewed and merged in Github page.
2. Submit to review
3. See updated fragments
4. Find latest accepted review request for this file

### Repository URL
New RR - https://gitlocalize.com/repo/2509/ru/review/9232/segments, latest accepted RR for this file - https://gitlocalize.com/repo/2509/ru/review/9211/segments

New RR - https://gitlocalize.com/repo/2509/ru/review/9234, latest accepted RR - https://gitlocalize.com/repo/2509/ru/review/9209

Maybe can be reproduced with [this file](https://gitlocalize.com/repo/2509/ru/rust-by-example/src/error/option_unwrap/and_then.md) ([latest accepted RR](https://gitlocalize.com/repo/2509/ru/review/9215))

### What is the current *bug* behavior?

For unchanged files suggested sending to review and review request has identical changed as latest accepted.

### What is the expected *correct* behavior?

For unchanged files button "Create Review Request" not shows (also RR not creates).

### Relevant logs and/or screenshots

<details>
<summary>Video</summary>

![video](https://user-images.githubusercontent.com/4323287/61493792-fb285a80-a9a3-11e9-8d0e-a73461de4881.gif)

</details>

**Comment by svasilenkov** [comment]
Has been fixed. Please check if it works well now.

**Comment by funkill** [comment]
Currently in merged RR shows link to appropriate PR. Maybe done
