### ISSUE TITLE
[Bug] PR creation fails for private Github repo

### ISSUE THREAD

**Issue by Nickersoft** [gitlocalize/feedback#64]
### Summary

I know this has been posted before, but the last issue on the bug I could find was from 2017 and has since been marked as resolved. Attempting to create a PR from the "Review Request" page results in an infinite spinning wheel. Checking the developer tools, the network request to `https://gitlocalize.com/repo/2634/es/review/9387.json` returns a 304 status with the body content:

```
{"status":"failed"}
```

I'm not sure if there are additional permissions I need to grant on Github in order to fix this. The error itself doesn't lend much insight.

### Steps to reproduce

Press the "Create PR" / "Retry" button on the Review Request page (https://gitlocalize.com/repo/2634/es/review/9387)

### Repository URL

https://gitlocalize.com/repo/2634 (private repo, so ideally only available to the GitLocalize team)

### What is the current *bug* behavior?

The "Create PR" functionality doesn't work. The spinner hangs, saying "Creating a pull request to the repo" indefinitely.

### What is the expected *correct* behavior?

A PR should be created and conveyed back to the user

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/2104129/62404966-e32d0b00-b54d-11e9-999a-770a9e445f34.png)

![image](https://user-images.githubusercontent.com/2104129/62404973-ecb67300-b54d-11e9-90df-e3576bf6eeb7.png)

### Possible fixes

Seeing a GitLocalize endpoint is failing, my guess is that there's an issue on the server preventing it from communicating to Github correctly.

**Comment by svasilenkov** [comment]
It is not reproducible at the moment. Please check if it is still not working correctly.

**Comment by svasilenkov** [comment]
@Nickersoft Could you please check if you still have problem with creating pull request.

**Comment by Nickersoft** [comment]
@svasilenkov This issue originally did resolve itself eventually, though I've noticed this problem has cropped up again. This time, the page refreshes, throws a 302 redirect in the console, and shows "Failed to create pull request". Are you able to reproduce? I've tried on both Brave and Chrome and the same issue occurs on both. 

Also, attempting to download the translated lproj file throws a 404, so I have no way of getting my translations off of GitLocalize and into my repo lol.

**Comment by ilyaspiridonov** [comment]
@Nickersoft Just a heads-up that we're looking into this

**Comment by ilyaspiridonov** [comment]
@Nickersoft It looks like we are having some troubles integrating with your private repo - is it possible that it earlier belonged to an organization, which was later removed? 
In any case, can we ask you to perform the following actions to reset the integration, as a workaround: 

1. Open this page:
  https://github.com/apps/gitlocalize-app/installations/new/permissions?suggested_target_id=12766812&state=installation
2. Select “Only select repositories” radio button.
3. Press “Select repositories” and choose “ios” repository you would like to give access to.
4. Press “Install & Authorize” button at the bottom of the page.

Please let me know when it's done. 
Thank you!
