### ISSUE TITLE
Tags moved after PR

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#68]
### Summary

Sometimes after merge PR tags moves to N positions.

### Steps to reproduce

1. Translate file with inline code blocks
2. Create Review Request.
3. Send PR
4. Accept PR
5. Sync repo
6. Open translated file

### Repository URL

We found this in https://gitlocalize.com/repo/2699/ru/async-book/src/07_workarounds/04_send_approximation.md but this behavior exists on different files and repos and we can't determine appearance algorithm.

### What is the current *bug* behavior?

Tags moved in N positions.

### What is the expected *correct* behavior?

Tags not moves.

### Relevant logs and/or screenshots
<details> <summary>Screenshots</summary>

<img width="1131" alt="Снимок экрана 2019-09-16 в 12 53 03" src="https://user-images.githubusercontent.com/4323287/64949799-866d8180-d869-11e9-8354-9e5818f8e9b0.png">
<img width="1134" alt="Снимок экрана 2019-09-16 в 12 53 10" src="https://user-images.githubusercontent.com/4323287/64949800-866d8180-d869-11e9-870b-340ed43942f9.png">

</details>

**Comment by svasilenkov** [comment]
Thanks for the feedback!

**Comment by svasilenkov** [comment]
The problem has been fixed, please check with your files.
