### ISSUE TITLE
Button "Create Review Request" shows on unchanged files

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#69]
### Summary

After merging PR and not changing translation Gitlocalize shows "Create Review Request" button

### Steps to reproduce

1. Translate file `A`
2. Send this file to review
3. Send PR
4. Accept PR
5. Sync project
6. Open file `A`.
7*. If send new RR and PR, created PR can be empty.

### Repository URL

https://gitlocalize.com/repo/2699/ru/async-book/src/07_workarounds/04_send_approximation.md and other

### What is the current *bug* behavior?

After merging PR (without any other changes on Github or Gitlocalize) and syncing project shows "Create Review Request" button.

### What is the expected *correct* behavior?

After merging PR and syncing project "Create Review Request" button not shows until changes are made.

**Comment by svasilenkov** [comment]
Thank you for submitting the issue. We'll find the cause of the problem and fix it.

**Comment by svasilenkov** [comment]
We've fixed the problem.

**Comment by amandastevens** [comment]
We just started using GitLocalize to translate our software documentation a few weeks ago and we are having this issue. For 2 files the translation was made, a review request was sent, the review was done, a pull request was made, the pull request was merged, and the translation was synced. Yet, the "Create Review Request" button is appearing beside the 2 files. You can see it in the screenshot next to the single-sign-on and appendix-1 files.

![Admin Guide translation status](https://user-images.githubusercontent.com/35044512/89446966-dc197980-d71a-11ea-8311-ee869d3dd6da.png)
