### ISSUE TITLE
Can’t fix the conflict

### ISSUE THREAD

**Issue by inouetakuya** [gitlocalize/feedback#7]
### Summary

Can't fix the conflict on ja/en/guide/directory-structure.md

### Repository URL

https://gitlocalize.com/repo/100/ja/en/guide/directory-structure.md

### Relevant logs and/or screenshots

I had tryed to fix the conflict with pull request on github, but the conflict have not fixed yet.

* https://github.com/nuxt/docs/pull/210

**Comment by sotayamashita** [comment]
@inouetakuya I have fixed with GUI. When the conflict occurs, please try to fix the issue with GUI first. Does it make sense?

**Comment by inouetakuya** [comment]
Sorry, I don't know how to fix the issue with GUI 😢

**Comment by inouetakuya** [comment]
I have gotten how to fix the conflicts with GUI at https://gitlocalize.com/repo/100/ja/en/guide/modules.md 😄
