### ISSUE TITLE
Edit base language text/content 

### ISSUE THREAD

**Issue by bogdy29** [gitlocalize/feedback#70]
### Summary

As a newspaper editor, I edit daily y blog and I want to introduce text/content in English (base language) and other 5 languages.

Since I am not a developer, I don't have access to code, I can't edit English text/content in web User Interface?

### Steps to reproduce

Open the app and try to edit base language (English)

### What is the expected *correct* behavior?

Click on base language and introduce text. 

### Possible fixes

Make the base language field, editable.

**Comment by svasilenkov** [comment]
Thank you for the suggestion, we've added it in our to-do list.
