### ISSUE TITLE
Error 500 on settings tab

### ISSUE THREAD

**Issue by mindw0rm** [gitlocalize/feedback#71]
### Summary

I added a _private_ repository of mine to GitLocalize. For the only language to translate to I chose one that already existed. 
Everything seems to work, I could view the existing translation, so access to the repository doesn't seem to be an issue. 
However, when I try to open the 'settings' tab of the repository, an error 500 is shown. 
All other tabs are accessible.

### Steps to reproduce

Connect  to a private repository on Github. [I don't know if the fact that the repository is private has anything to do with the bug and I haven't tries it with other repositories yet, since I can't find a way to remove them again (I guess that's on the settings tab?)]
When asked for languages, specify one where the trnaslation already exists. [again, I have no idea if this is relevant. Maybe the bug will happen also if the language does _not_ exist yet?]
Open the settings tab. [well, before I did this, I dove into the directory structure and opened the trnaslation page for the specified language, and went back to the repository ovberview, and opened the team tab before trying the settings tab]

### Repository URL

https://gitlocalize.com/repo/3365

### What is the current *bug* behavior?

I see this:
![500](https://user-images.githubusercontent.com/6404575/67611900-2211dc00-f79e-11e9-8866-3ab6d4bd26b2.png)

### What is the expected *correct* behavior?

I see the settings tab for my project.

### Relevant logs and/or screenshots
see above

### Possible fixes

No idea - internal server error is internal :/

Well, I _suspect_ that it has something to do with the fact that the repository is private - but then again, I guess that isn't so rare that it wouldn't have happened before, but I didn't find another issue about it.

**Comment by ilyaspiridonov** [comment]
We've fixed this, pls check

**Comment by mindw0rm** [comment]
Page is viewable now, thanks.
