### ISSUE TITLE
[Enchancement]: Make shortcuts work in the translation edit box

### ISSUE THREAD

**Issue by nlinker** [gitlocalize/feedback#72]
Hello,

It would be really great, if some shortcuts worked in the small translation window.
Especially `Escape` and `Ctrl+Enter` would be very helpful, since it enabled _mouseless_ workflow at least for a file.
![image](https://user-images.githubusercontent.com/940363/68881984-6c9ccd80-0738-11ea-9471-79a829a866a8.png)
(so these buttons one cannot press without mouse)

Thanks!

**Comment by ilyaspiridonov** [comment]
Thanks Nick, good point. We're adding this to our roadmap

**Comment by nlinker** [comment]
It is pity that it has marked `wontfix`, since I still find the editing process not very convenient.

**Comment by ilyaspiridonov** [comment]
Thanks Nick, we still have this on our roadmap, it's just that some core issues are of higher priority at the moment.

**Comment by nlinker** [comment]
refresh

**Comment by ilyaspiridonov** [comment]
@nlinker We've added support for the ESC and Ctrl-Enter (Cmd-Enter) shortcuts. Feel free to try it out :)

**Comment by nlinker** [comment]
Oh, thanks! This is really well worth waiting for!
