### ISSUE TITLE
BUG: Broken rendering translation into markdown

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#73]
### Summary

Your web editor during editing presents markup with special tags `{/code}` and etc. When editing is finished, this layout is not displayed correctly in the preview mode. See attached files.

### Repository URL

https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch06-01-defining-an-enum.md

#### Edit mode

![edit_mode](https://user-images.githubusercontent.com/20382553/69800653-c2687f80-11e6-11ea-87fa-80facea96057.png)

#### View mode

![rendering_mode](https://user-images.githubusercontent.com/20382553/69800660-c5fc0680-11e6-11ea-8808-cf85ecf9ba96.png)

Special tags not convert markdown.

**Comment by svasilenkov** [comment]
Thank you for the feedback!

**Comment by ava57r** [comment]
Often it is broken when use machine translate.
Creates new special tags that are not present in the original text fragment.

**Comment by svasilenkov** [comment]
The problem has been fixed.

**Comment by ava57r** [comment]
Thanks.
I check.

**Comment by ilyaspiridonov** [comment]
Fixed
