### ISSUE TITLE
[Bug]: "100%" dont fit in the badge 

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#75]
### Summary

When install badge in completed translation "100%" want fit in small space and numbers overlap each other. For Smaller numbers percents not overlaps.

### Steps to reproduce

1. Fully translate some repo
2. Go to Badge" tab and see "Preview"

### Repository URL

https://github.com/rust-lang-ru/rust-by-example/blob/master/README.md

https://gitlocalize.com/repo/2509/badge

### What is the current *bug* behavior?

Numbers overlap each other and "100%" not fit in percent part of badge.

### What is the expected *correct* behavior?

Numbers not overlap each other.

### Relevant logs and/or screenshots

For "100%":
<img width="224" alt="Снимок экрана 2020-01-26 в 13 07 17" src="https://user-images.githubusercontent.com/4323287/73133742-ee588380-4024-11ea-9c5d-4c989d2eb6db.png">

For smaller number:
<img width="142" alt="Снимок экрана 2020-01-26 в 13 15 33" src="https://user-images.githubusercontent.com/4323287/73133743-ee588380-4024-11ea-8119-4f80652fde70.png">

**Comment by svasilenkov** [comment]
Thanks! We have fixed this.

**Comment by ilyaspiridonov** [comment]
Fixed, closing
