### ISSUE TITLE
原文と日本語との対応にズレがある

### ISSUE THREAD

**Issue by inouetakuya** [gitlocalize/feedback#8]
### Summary

原文と日本語との対応にズレがあります。

### Repository URL

https://gitlocalize.com/repo/100/ja/en/guide/vuex-store.md

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/634357/30117245-999d35b2-935a-11e7-9816-6f78dfa43a49.png)

**Comment by sotayamashita** [comment]
@inouetakuya 確認が遅れてしまって申し分けありません。確かにずれていますね。原因究明をして同じ問題が発せしないように修正致します。

**Comment by sotayamashita** [comment]
@inouetakuya 

#### 事象

**Comment by sotayamashita** [comment]
@inouetakuya 今回はかなり特殊なケースなのでこちらで修正させていただきました。また今後同じような問題が起きたときのために問題解消のための方法を実装致しました。

この度はご迷惑をおかけしまして、大変申し訳ございませんでした :bow:

**Comment by inouetakuya** [comment]
修正されていることを確認しました。対応ありがとうございました！！
