### ISSUE TITLE
Only merged translations should be accounted in the completion overview

### ISSUE THREAD

**Issue by whiver** [gitlocalize/feedback#80]
### Summary

When going to the overview page, the completion ratio for each language is taking the unreviewed translations into account. This is misleading as we may think that the translation is complete and prevent from clicking on the language, which then displays the unreviewed translations count.

### Steps to reproduce

- have an incomplete translation for a language: notice that the completion ratio is less than 100%
- complete the translation without submitting the pull request
- go back to the overview page: the completion ratio is now displaying 100%, even if the translation is in fact not completed.

### Repository URL

Any repo.

### What is the current *bug* behavior?

The completion ratio is including unreviewed translations.

### What is the expected *correct* behavior?

The completion ratio based on the *merged* translations.

### Relevant logs and/or screenshots

- Completion is set to 100% in the overview page:
![image](https://user-images.githubusercontent.com/394565/78998565-3168c400-7b49-11ea-9fd4-6443ed6696de.png)

- Though there is one translation under review that is adding new strings
![image](https://user-images.githubusercontent.com/394565/78998726-7f7dc780-7b49-11ea-8f26-181b02b7d4f0.png)

### Possible fixes

I would suggest only displaying the completion ration of the *merged* translations, or at least indicate in the overview page the number of unreviewed translations pending (or both, that would be the best!)

**Comment by ilyaspiridonov** [comment]
@whiver Thanks for submitting this William, we'll probably start with showing the number of pending Review Requests on the overview page. I've created a ticket for our dev team, can't say how soon we'll be able to add this though.

**Comment by whiver** [comment]
Thanks for your reactivity and for your answer!

**Comment by huangjj27** [comment]
What if Ihave pushed the translation to GitHub directly?

**Comment by whiver** [comment]
@huangjj27 Well then the new translations will be taken into account for the completion rate, as the translations will be updated. I'm not sure to understand your comment: is there something I missed?

**Comment by huangjj27** [comment]
> I'm not sure to understand your comment: is there something I missed?

You've answered my question, thanks! I was just wondering if I could sync my translation onto GitLocalize if I pushed it GitHub directly.
