### ISSUE TITLE
Breaks the formatted code in the translation

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#82]
I only sent PR to github without editing the file.

This file itself changed format code blocks
![screen_20200505](https://user-images.githubusercontent.com/20382553/81049026-1417e300-8ec6-11ea-986c-e9a9483774ec.png)

Dropped all `LF`.
Example file 
https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch03-02-data-types.md.

**Comment by ava57r** [comment]
It is correct on github.

![screen-20200505_2](https://user-images.githubusercontent.com/20382553/81050895-7e7e5280-8ec9-11ea-8917-493fca66c140.png)

**Comment by yuriy-ln** [comment]
I'm confirm that.
Looks like gizlocalize renders code incorrectly after page is loaded from db.

**Comment by svasilenkov** [comment]
Thanks for reporting this problem. Now it is fixed.

**Comment by ava57r** [comment]
Not works =(
I changed 1 segment without code.
 
File is corrupted
https://gitlocalize.com/repo/3025/ru/rustbook-en/src/ch04-02-references-and-borrowing.md

PR Github
https://github.com/rust-lang-ru/book/pull/233/files

**Comment by ava57r** [comment]
refresh...

**Comment by blandger** [comment]
Is it fixed?

**Comment by ilyaspiridonov** [comment]
@blandger @andreevlex This seems to be working fine now: 
https://gitlocalize.com/repo/5126/ru/ch04-02-references-and-borrowing.md
https://github.com/gitlocalizetest/gltest/blob/fe16feb3e3477fc1c3d877a53c15b7cf0cc0e171/ru/ch04-02-references-and-borrowing.md
Thank you!

**Comment by blandger** [comment]
@ilyaspiridonov 
можно ли что-то сделать со след. поведением...??

после заливки нового англ.текста в репу, русские абзацы практически не изменились, или изменились не значительно.
После линковки "почти не изменившихся текстов на русс." - хотелось бы, чтобы они остались для дальнейшей правки (или можно было бы хотя посмотреть/скопировать тот текст при необходимости), но практически весь русский текст "улетает" и "хочет опять перевода", за исключение 4-х абзацев внизу, которые система "посчитала идентичными".

https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch20-03-graceful-shutdown-and-cleanup.md

**Comment by ilyaspiridonov** [comment]
@blandger я посмотрел - вроде бы все непереведенные сегменты подтягиваются из памяти переводов (там примерно секунду нужно подождать, чтобы подтянулось), то есть можно сделать Apply, подтянется старый перевод, в который можно внести правки. http://joxi.ru/vAWbMLZHq7wkE2
Или я не совсем так понял?

**Comment by blandger** [comment]
@ilyaspiridonov спасибо, не знал как это работает. Да, старый подтягивает.
