### ISSUE TITLE
Translations not 100% complete

### ISSUE THREAD

**Issue by chalkedgoose** [gitlocalize/feedback#85]
### Translations not 100% complete
My translations are not 100% complete even when they are. 

### Steps to reproduce
Translate a longer document and it results in issues with the doc only being 
99% done. 

### Repository URL

https://github.com/CSumm/helpmepoc

### What is the current *bug* behavior?
When we are translating a longer doc we encounter a ton of issues with it 
saying it is incomplete.

<img width="1016" alt="Screen Shot 2020-06-24 at 6 38 58 PM" src="https://user-images.githubusercontent.com/26678464/85643769-f9522700-b649-11ea-8540-3141a77667d9.png">

### What is the expected *correct* behavior?
100% completion

### Possible fixes

An override button for translators who 
are sure that they are done with the full translation
that can let the app know it should be 100% and it 
could also be used to get around buggy behavior.

**Comment by chalkedgoose** [comment]
<img width="434" alt="Screen Shot 2020-06-24 at 6 44 56 PM" src="https://user-images.githubusercontent.com/26678464/85644081-d07e6180-b64a-11ea-9404-33cdafbe1308.png">

**Comment by ilyaspiridonov** [comment]
Hi @calba5141114 
Thanks for reporting this. Can you send a link to the file you're experiencing troubles with? 
Thank you!

**Comment by chalkedgoose** [comment]
Thanks for the quick response @ilyaspiridonov here is the file https://github.com/CSumm/helpmepoc/blob/master/docs/es/resources/README.md

**Comment by ilyaspiridonov** [comment]
I can't seem to find the file you're referencing to, but the Japanese version looks good, can you please check? 
https://gitlocalize.com/repo/4905/ja/docs/README.md
Feel free to reopen if there's an update on this. Thank you!
