### ISSUE TITLE
Country codes for every language

### ISSUE THREAD

**Issue by larsb24** [gitlocalize/feedback#86]
### Country codes for every language

I recently started using GitLocalize and I encountered the "bug" that some languages support country codes and others not.

### Steps to reproduce

- creating a gitlocalize project and try adding languges that don't have a country code

### Repository URL

Any repo.

### What is the current *bug* behavior?

GitLocalize creates only "%languagecode%.json" for languages that don't have a country code but it would be nice to have a "%languagecode%-%countrycode%.json" option for every language
This problem results in some languages being like "de-DE.json" and others being like "pl.json"

### What is the expected *correct* behavior?

A .json file that contains language and country code in the name.

### Possible fixes

Add a switch to settings to allow users to enable country code for languages without country code

**Comment by ilyaspiridonov** [comment]
Hi @larsb24 thanks for submitting this. We're actually working on an update which will allow specifying custom language codes when adding languages (so you should be able to specify language codes with country codes, like de-DE in your example) -- which will affect the paths as well. 
We already have this on our testing servers, so should probably roll out in a week or so. 
Stay tuned.

**Comment by larsb24** [comment]
Ok Nice, thanks for the fast reply.

**Comment by ilyaspiridonov** [comment]
@larsb24 You should now be able to add languages with custom codes by clicking [Manage Languages] in project overview. 
Thanks!
