### ISSUE TITLE
Code blocks to html entities in markdown

### ISSUE THREAD

**Issue by funkill** [gitlocalize/feedback#89]
### Summary

Code from code blocks parses as html and corrupts. E.g. `-->` converts to `--&gt;` ([link](https://github.com/rust-lang-ru/translations/pull/70/files#diff-883162f680f4d752c720dcbc25d6228aR40)) or `<:sys_common::backtrace::_print::displaybacktrace as core::fmt::display="">::fmt` parsed as tag and after all adds close tag ([link](https://github.com/rust-lang-ru/translations/pull/70/files#diff-883162f680f4d752c720dcbc25d6228aR111))

### Steps to reproduce

1. create code block in markdown

<pre><code>```
-->
<:some-words> and text after
new string
```</code></pre>

2. save transaltion w/o changes
3. see translated segment

### Repository URL

https://gitlocalize.com/repo/2799/ru/originals/announcements/2020-10-05-Rust-1.47.md
https://github.com/rust-lang-ru/translations/pull/70/files

### What is the current *bug* behavior?

Special symbols converts to html entities and pair `<>` can parses as html tag


### What is the expected *correct* behavior?

Special symbols save as in original and pair `<>` not parses as html tag

### Relevant logs and/or screenshots

<img width="1028" alt="Снимок экрана 2020-10-07 в 17 54 24" src="https://user-images.githubusercontent.com/4323287/95341371-b5f09100-08a5-11eb-9d8a-76ce971ec709.png">
<img width="957" alt="Снимок экрана 2020-10-07 в 17 55 18" src="https://user-images.githubusercontent.com/4323287/95341381-b8eb8180-08a5-11eb-9b5f-d5ca93eadb45.png">

**Comment by ava57r** [comment]
And here
https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch13-02-iterators.md

![screen-2020-10-15_1](https://user-images.githubusercontent.com/20382553/96094830-83165080-0ed6-11eb-9421-fe6bc13515b1.png)

**Comment by ilyaspiridonov** [comment]
@ava57r Hi, thanks - can you confirm this looks good now everywhere?

**Comment by ava57r** [comment]
I confirm.
https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch13-02-iterators.md

**Comment by ava57r** [comment]
another example https://github.com/rust-lang-ru/book/pull/691/files
