### ISSUE TITLE
Wrong tag <comment></comment> to Github PRs

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#90]
Hello
Why wasn't it replace?
GL repo tag `{comment}{/comment}` sometimes makes tag `<comment></comment>.`

in repo 
https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch02-00-guessing-game-tutorial.md

```text
({a0}{em1}авто-импорт - prelude{/em1}{/a0}){comment2} <!-- -->{/comment2}
```

in GH PR
https://github.com/rust-lang-ru/book/pull/370/files
Example 

```markdown
([*авто-импорт - prelude*](https://doc.rust-lang.org/std/prelude/index.html))<comment> <!-- --></comment>
```

**Comment by svasilenkov** [comment]
Thanks for reporting the issue. We'll find out how to fix this.

**Comment by ava57r** [comment]
This tag is replaced differently in each file.

**Comment by ava57r** [comment]
I am waiting fix

**Comment by svasilenkov** [comment]
I'm sorry for the delay. To fix the problem you should change this paragraph:

`По умолчанию, Rust автоматически подключает несколько типов данных в область видимости каждой программы ({a0}{em1}авто-импорт - prelude{/em1}{/a0})<!-- {comment2}{/comment2} -->. Если типы данных, которые вы хотите использовать в программе не входят в авто-импорт, то вам нужно подключить их в область видимости явно с помощью выражения {code3}use{/code3}. Библиотека ввода/вывода {code4}std::io{/code4} предоставляет множество полезных функциональных возможностей, включая обработку вводимых данных пользователя.`

To this value:

`По умолчанию, Rust автоматически подключает несколько типов данных в область видимости каждой программы ({a0}{em1}авто-импорт - prelude{/em1}{/a0}){comment2}игнорируйте{/comment2}. Если типы данных, которые вы хотите использовать в программе не входят в авто-импорт, то вам нужно подключить их в область видимости явно с помощью выражения {code3}use{/code3}. Библиотека ввода/вывода {code4}std::io{/code4} предоставляет множество полезных функциональных возможностей, включая обработку вводимых данных пользователя.`

**Comment by SomeAkk** [comment]
@svasilenkov seems it's not working as you recommend. 

Let look at example (also we change some translation, but `<comment></comment>` steel here).

Our original text:
```
By default, Rust brings only a few types into the scope of every program in
[the *prelude*][prelude]<!-- ignore -->. If a type you want to use isn’t in the
prelude, you have to bring that type into scope explicitly with a `use`
statement. Using the `std::io` library provides you with a number of useful
features, including the ability to accept user input.
```

Text which we get in GL:
`
By default, Rust brings only a few types into the scope of every program in {a0}the {em1}prelude{/em1}{/a0}{comment2} ignore {/comment2}. If a type you want to use isn’t in the prelude, you have to bring that type into scope explicitly with a {code3}use{/code3} statement. Using the {code4}std::io{/code4} library provides you with a number of useful features, including the ability to accept user input.
`

Our translation in GL which we try to set in:

`
По умолчанию, Rust автоматически подключает несколько типов данных в область видимости каждой программы (данная технология известна как {em0}авто-импорт{/em0} или {a1}{em2}prelude{/em2}{/a1} {comment2}{/comment2}). Если типы данных, которые вы хотите использовать в программе не входят в авто-импорт, то вам нужно подключить их в область видимости явно с помощью выражения {code4}use{/code4}. Использование библиотеки ввода/вывода {code5}std::io{/code5} предоставляет множество полезных функциональных возможностей, включая обработку вводимых данных пользователя - по этой причине мы и импортировали её.
`

Translation which sets in GL after we submit our (in previous step): do not understand why, but we gets "comment3"

`
По умолчанию, Rust автоматически подключает несколько типов данных в область видимости каждой программы (данная технология известна как {em0}авто-импорт{/em0} или {a1}{em2}prelude{/em2}{/a1} {comment3}{/comment3}). Если типы данных, которые вы хотите использовать в программе не входят в авто-импорт, то вам нужно подключить их в область видимости явно с помощью выражения {code4}use{/code4}. Использование библиотеки ввода/вывода {code5}std::io{/code5} предоставляет множество полезных функциональных возможностей, включая обработку вводимых данных пользователя - по этой причине мы и импортировали её.
`

Our translated text in GitHub after completed PR in GL: steel have `<comment></comment>`

`
По умолчанию, Rust автоматически подключает несколько типов данных в область видимости каждой программы (данная технология известна как <em>авто-импорт</em> или [*prelude*](https://doc.rust-lang.org/std/prelude/index.html) <comment></comment>). Если типы данных, которые вы хотите использовать в программе не входят в авто-импорт, то вам нужно подключить их в область видимости явно с помощью выражения <code>use</code>. Использование библиотеки ввода/вывода <code>std::io</code> предоставляет множество полезных функциональных возможностей, включая обработку вводимых данных пользователя - по этой причине мы и импортировали её.
`

**Comment by ava57r** [comment]
> It was never added to the HTML specification and is not supported by modern browsers.

Read more: https://html.com/tags/old-comment-tag/

Why do you support this tag?

**Comment by ivanych** [comment]
I ran into this too. This behavior creates a lot of problems, in fact.

**Comment by svasilenkov** [comment]
Now it's fixed, could you check once more?

**Comment by ava57r** [comment]
@svasilenkov I checked.
It does not work for https://github.com/rust-lang-ru/book/pull/595

**Comment by svasilenkov** [comment]
We've made some changes that should help fix the problem. Could you please check once again?

**Comment by ava57r** [comment]
It's clear.
https://github.com/rust-lang-ru/book/pull/601
https://github.com/rust-lang-ru/book/pull/600
https://github.com/rust-lang-ru/book/pull/599
https://github.com/rust-lang-ru/book/pull/598

It's works.
Thanks!
