### ISSUE TITLE
Mysterious MD source transformations into HTML pieces

### ISSUE THREAD

**Issue by blandger** [gitlocalize/feedback#91]
### MD code is transformed into HTML sometimes.
Pulling PR from GL back into GH sometime shows unclear difference. That  can't be tracked easily when those changes has happen. MD source pushed from GL is not correct although.

### Steps to reproduce
Unknown unfortunately.

### Repository URL
https://gitlocalize.com/repo/4579/ru/rustbook-en/src/ch15-06-reference-cycles.md

### What is the current *bug* behavior?
Third section at the end on page.

GL Eng view in editor is correct: Also discussed were the {code0}Deref{/code0} and {code1}Drop{/code1} traits, ........... them using {code2}Weak<T>{/code2}.

GL Rus view in editor is correct: Мы обсудили также типажи {code0}Deref{/code0} и {code1}Drop{/code1}, ......... с помощью типа {code2}Weak<T>{/code2}.

Original MD eng. (code have a back tick symbols) : Also discussed were the `Deref` and `Drop` traits, ......... them using `Weak<T>`.

MD rus. pushed into GH (NO back tick md symbols but there is a HTML code): Мы обсудили также типажи <code>Deref</code> и <code>Drop</code>, ..... помощью типа <code>Weak<t></t></code>.

See that issue in commit here :
https://github.com/rust-lang-ru/book/pull/401/commits/acee4e2cda08cc50bec388dc2ec2949aee87edc9

### What is the expected *correct* behavior?
Russian section should look as correct MD (with back tick symbols) when it's committed back into GH:

Мы обсудили также типажи `Deref` и `Drop`, ........ помощью типа `Weak<T>`.

**Comment by svasilenkov** [comment]
@blandger As I can see in the lastest GitLocalize commit made for this file the problem is fixed:

https://github.com/rust-lang-ru/book/commit/a429c5727654991b19e3179f00d3027b7963a856#diff-ae7b5f0f016a338b05a29574ba06ee8428d50df4eb33286031b9539a6f6815b3

Please check if these code blocks are now processed by GitLocalize correctly.

**Comment by blandger** [comment]
close that now. We'll check that later on next translation attempts.

**Comment by huangjj27** [comment]
Never mind the HTML styles blocks on  GitLocalize (like `{code0} some code {/code0}`), those block will be correctly linked and translated into markdown.
