### ISSUE TITLE
MD links sometimes converted into HTML links

### ISSUE THREAD

**Issue by blandger** [gitlocalize/feedback#92]
### Steps to reproduce
Hard to say how and when that has happen in past.

### Repository URL
See commit :
https://github.com/rust-lang-ru/book/pull/400/commits/8e236575a9ee7ce148b2f9611875081336c37adb

### What is the current *bug* behavior?
GL editor view ENG:
 {a6}“Preventing Reference Cycles: Turning an {code7}Rc<T>{/code7} into a {code8}Weak<T>{/code8}”{/a6}{comment9} ignore {/comment9} section.

GL editor view RUS:
{a6}«Предотвращение циклических ссылок: превращением {code7}Rc<T>{/code7} в {code8}Weak{/code8}»{/a6}{comment9}  {/comment9}.

Original ENG md code:
[“Preventing Reference Cycles: Turning an `Rc<T>` into a `Weak<T>`”][preventing-ref-cycles] section.

RUS code pushed from GL into GH:
< a href="ch15-06-reference-cycles.html#preventing-reference-cycles-turning-an-rct-into-a-weakt" > «Предотвращение циклических ссылок: превращением `Rc<T>` в  < code data-md-type = "raw_html" > Weak < / code> » < /a> < !--  -->.

### What is the expected *correct* behavior?
Better but NOT QUITE correct code could be :
< a href="ch15-06-reference-cycles.html#preventing-reference-cycles-turning-an-rct-into-a-weakt" >«Предотвращение циклических ссылок: превращением `Rc<T>` в `Weak<T>`» < / a > < !--  -- >.

**Completely correct MD code should be like :** 
[“Предотвращение циклических ссылок: превращением `Rc<T>` в `Weak<T>`”][preventing-ref-cycles] главе.

**Comment by svasilenkov** [comment]
Thanks for the feedback. We'll fix the cause of the problem.

**Comment by svasilenkov** [comment]
Could you test that again? Should work well now.
