### ISSUE TITLE
Typo in `Add Repository` section

### ISSUE THREAD

**Issue by p0lunin** [gitlocalize/feedback#94]
Typo in `Add Repository` section (https://gitlocalize.com/repo/new)

![image](https://user-images.githubusercontent.com/48922415/99913774-2b9fa780-2d02-11eb-800f-aaff8edcded4.png)

Langauge, but must be Language.

**Comment by svasilenkov** [comment]
Thanks for reporting this. We'll fix it.

**Comment by svasilenkov** [comment]
We've fixed it.
