### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#95]
Hello.
I am repeating my request from issue
https://github.com/gitlocalize/feedback/issues/83

Need REST API.

Thanks.

**Comment by ilyaspiridonov** [comment]
Thanks, can you describe the business case in more detail, and specifically which API methods you believe would make sense to expose?

**Comment by ava57r** [comment]
Hello.

We have an own translation dictionary.

For example. Find all "трэйт" to replace "типаж" from our dictionary in a book.

**Comment by ilyaspiridonov** [comment]
@ava57r Thanks for the details. 
Would you like to be included in the beta testing for our glossary feature? 
<img width="1568" alt="Screen Shot 2021-01-14 at 17 59 07" src="https://user-images.githubusercontent.com/8548803/104608517-08a2cb80-5693-11eb-8a9c-6282804446ff.png">
In case yes, feel free to send the list of project for which the glossary should be enabled at ilya@gitlocalize.com 

Updating content via API may not be the ideal solution. You should rather update translations on GitHub end (as the GitHub repo is the source of truth) -- those changes should be synced back in the the Gitlocalize projects.

**Comment by ava57r** [comment]
No. thanks.
I do not have enough time.
