### ISSUE TITLE
[Question] project source and target path from 2 different repos

### ISSUE THREAD

**Issue by SDSTony** [gitlocalize/feedback#98]
HI,

In order to configure Gitlocalize in a personal project, I'm currently checking out [Tensorflow-docs](https://github.com/tensorflow/docs-l10n). 

It seems that [source directory](https://github.com/tensorflow/docs-l10n/tree/master/site/en-snapshot) and [target directory](https://github.com/tensorflow/docs-l10n/tree/master/site/ko) must be in the same repo in order to use Gitlocalize. 

I wonder if we are able to configure source directory from repo A and target directory to a folder in repo B (another repo)?

Thanks.

**Comment by ilyaspiridonov** [comment]
> I wonder if we are able to configure source directory from repo A and target directory to a folder in repo B (another repo)?

Unfortunately, this is not something that's supported now, but we do plan to add support for that. Which project are you trying to add? If it's the Tensorflow project that you're adding, there's a project for that repo already on GitLocalize: http://gitlocalize.com/tensorflow/docs-l10n/

**Comment by SDSTony** [comment]
> Which project are you trying to add? 

Thank you for the answer. 

I'm trying to GitLocalize [https://github.com/Pseudo-Lab/Tutorial-Book](https://github.com/Pseudo-Lab/Tutorial-Book). It has deep learning tutorials in PyTorch. Trying to translate from Korean to English.
