### ISSUE TITLE
[Help Wanted] Submitting long time with no respone

### ISSUE THREAD

**Issue by mokurin000** [gitlocalize/feedback#99]
It runs for hours...

![图片](https://user-images.githubusercontent.com/34085039/107156120-60450600-69b7-11eb-90b8-6c4d06c8d14c.png)

**Comment by ilyaspiridonov** [comment]
Hi, as a temporary solution - please select Chinese (zh), then edit the language code as needed (for example, zh-cn, depending on which one you need), and then click Submit.
Please let me know if this works @poly000

**Comment by mokurin000** [comment]
> Hi, as a temporary solution - please select Chinese (zh), then edit the language code as needed (for example, zh-cn, depending on which one you need), and then click Submit.
> Please let me know if this works @poly000

yes
